name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
            python-version: '3.12'
    - run: |
        mkdir temp
        mkdir -p ./themes/medius
        wget -P temp https://github.com/onur/medius/archive/refs/heads/master.zip
        unzip temp/master.zip -d temp
        mv temp/medius-master themes/medius
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pelican content -o output -s publishconf.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
